package com.cil.shift.feature.onboarding.presentation.suggestions

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.cil.shift.feature.habits.domain.model.Frequency
import com.cil.shift.feature.habits.domain.model.Habit
import com.cil.shift.feature.habits.domain.usecase.CreateHabitUseCase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.datetime.DayOfWeek

class HabitSuggestionsViewModel(
    private val createHabitUseCase: CreateHabitUseCase
) : ViewModel() {

    private val _state = MutableStateFlow(HabitSuggestionsState())
    val state: StateFlow<HabitSuggestionsState> = _state.asStateFlow()

    fun onEvent(event: HabitSuggestionsEvent) {
        when (event) {
            is HabitSuggestionsEvent.CategorySelected -> {
                _state.update { it.copy(selectedCategory = event.category) }
            }

            is HabitSuggestionsEvent.HabitToggled -> {
                _state.update { currentState ->
                    val newSelectedHabits = if (currentState.selectedHabits.contains(event.habitId)) {
                        currentState.selectedHabits - event.habitId
                    } else {
                        currentState.selectedHabits + event.habitId
                    }
                    currentState.copy(selectedHabits = newSelectedHabits)
                }
            }

            is HabitSuggestionsEvent.CreateSelectedHabits -> {
                createSelectedHabits()
            }

            is HabitSuggestionsEvent.SkipSuggestions -> {
                // Just complete without creating habits
            }
        }
    }

    private fun createSelectedHabits() {
        viewModelScope.launch {
            _state.update { it.copy(isCreating = true, error = null) }

            try {
                val selectedSuggestions = habitSuggestions.filter { suggestion ->
                    _state.value.selectedHabits.contains(suggestion.id)
                }

                selectedSuggestions.forEach { suggestion ->
                    val habit = Habit(
                        id = "", // Will be generated by repository
                        name = suggestion.name,
                        icon = suggestion.icon,
                        color = suggestion.color,
                        habitType = suggestion.habitType,
                        frequency = Frequency.Daily, // Default to daily for all suggestions
                        targetValue = suggestion.targetValue,
                        targetUnit = suggestion.targetUnit,
                        reminderTime = null,
                        createdAt = com.cil.shift.core.common.currentTimestamp()
                    )

                    createHabitUseCase(habit)
                }

                _state.update { it.copy(isCreating = false) }
            } catch (e: Exception) {
                _state.update {
                    it.copy(
                        isCreating = false,
                        error = e.message ?: "Failed to create habits"
                    )
                }
            }
        }
    }

    val isCompleted: Boolean
        get() = !_state.value.isCreating && _state.value.error == null &&
                _state.value.selectedHabits.isNotEmpty()
}
